#pragma once

#include"shinsei/struct.h"
#define HAVE_SSIZE_T 1
#include"python3/Python.h"

#ifdef _SHINSEI_OS_CPP
#define this _this
extern "C"{
#endif

#ifdef _SHINSEI_OS_CONSTEXPR
	static _SHINSEI_OS_CONSTEXPR size_t shinsei_ex_pystack_t_DEF_CAP=8;
#else
	#define shinsei_ex_pystack_t_DEF_CAP (size_t)8
#endif

typedef struct _SHINSEI_OS_ALIGN_BYTE{
	int_fast32_t ctrl;
	size_t size;
	size_t cap;
	PyObject** data;
}shinsei_ex_pystack_t;

// Constructors
_SHINSEI_LIB_API shinsei_ex_pystack_t* shinsei_ex_pystack_t_con()_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API shinsei_ex_pystack_t* shinsei_ex_pystack_t_conCapacity(const size_t cap)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API shinsei_ex_pystack_t* shinsei_ex_pystack_t_conAssign(const shinsei_ex_pystack_t*const restrict src)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API shinsei_ex_pystack_t* shinsei_ex_pystack_t_conAssignUnsafe(const shinsei_ex_pystack_t*const restrict src)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API shinsei_ex_pystack_t* shinsei_ex_pystack_t_conMove(shinsei_ex_pystack_t* const restrict src)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API shinsei_ex_pystack_t* shinsei_ex_pystack_t_conElement(const PyObject*const restrict val,const size_t cnt)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API shinsei_ex_pystack_t* shinsei_ex_pystack_t_conElementUnsafe(const PyObject*const restrict val,const size_t cnt)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API shinsei_ex_pystack_t* shinsei_ex_pystack_t_conArray(const PyObject**const restrict arr,const size_t len)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API shinsei_ex_pystack_t* shinsei_ex_pystack_t_conArrayUnsafe(const PyObject**const restrict arr,const size_t len)_SHINSEI_OS_NOEXCEPT;

// Destructor
_SHINSEI_LIB_API void shinsei_ex_pystack_t_dec(shinsei_ex_pystack_t *const restrict this)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API void shinsei_ex_pystack_t_decUnsafe(shinsei_ex_pystack_t *const restrict this)_SHINSEI_OS_NOEXCEPT;

// Capacity Management
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_expand(shinsei_ex_pystack_t*const restrict this,const size_t more_cap)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_shrink(shinsei_ex_pystack_t*const restrict this,const size_t less_cap)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_reserve(shinsei_ex_pystack_t* const restrict this,const size_t cap)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_shrinkToFit(shinsei_ex_pystack_t* const restrict this)_SHINSEI_OS_NOEXCEPT;

// Status
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_empty(const shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API size_t shinsei_ex_pystack_t_size(const shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API size_t shinsei_ex_pystack_t_capacity(const shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;

// Accessors
_SHINSEI_LIB_API PyObject* shinsei_ex_pystack_t_top(const shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API PyObject* shinsei_ex_pystack_t_topUnsafe(const shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API PyObject* shinsei_ex_pystack_t_at(const shinsei_ex_pystack_t*const restrict this,const size_t idx)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API PyObject* shinsei_ex_pystack_t_atUnsafe(const shinsei_ex_pystack_t*const restrict this,const size_t idx)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API PyObject** shinsei_ex_pystack_t_data(const shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;

// Modifiers
_SHINSEI_LIB_API void shinsei_ex_pystack_t_pop(shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API void shinsei_ex_pystack_t_popUnsafe(shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API void shinsei_ex_pystack_t_popArray(shinsei_ex_pystack_t*const restrict this,const size_t cnt)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API void shinsei_ex_pystack_t_popArrayUnsafe(shinsei_ex_pystack_t*const restrict this,const size_t cnt)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_push(shinsei_ex_pystack_t*const restrict this,const PyObject*const restrict val)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_pushUnsafe(shinsei_ex_pystack_t*const restrict this,const PyObject*const restrict val)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_pushArray(shinsei_ex_pystack_t*const restrict this,const PyObject**const restrict arr,const size_t len)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_pushArrayUnsafe(shinsei_ex_pystack_t*const restrict this,const PyObject**const restrict arr,const size_t len)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_pushElement(shinsei_ex_pystack_t*const restrict this,const PyObject*const restrict val,const size_t cnt)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_pushElementUnsafe(shinsei_ex_pystack_t*const restrict this,const PyObject*const restrict val,const size_t cnt)_SHINSEI_OS_NOEXCEPT;

// Utility
_SHINSEI_LIB_API void shinsei_ex_pystack_t_swap(shinsei_ex_pystack_t*const restrict this,shinsei_ex_pystack_t*const restrict src)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_clear(shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_clearUnsafe(shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_setSize(shinsei_ex_pystack_t*const restrict this,const size_t size)_SHINSEI_OS_NOEXCEPT;

_SHINSEI_LIB_API bool shinsei_ex_pystack_t_assign(shinsei_ex_pystack_t*const restrict this,const shinsei_ex_pystack_t*const restrict src)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_assignUnsafe(shinsei_ex_pystack_t*const restrict this,const shinsei_ex_pystack_t*const restrict src)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API void shinsei_ex_pystack_t_move(shinsei_ex_pystack_t*const restrict this,shinsei_ex_pystack_t* const restrict src)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API void shinsei_ex_pystack_t_moveUnsafe(shinsei_ex_pystack_t*const restrict this,shinsei_ex_pystack_t* const restrict src)_SHINSEI_OS_NOEXCEPT;

_SHINSEI_LIB_API bool shinsei_ex_pystack_t_attach(shinsei_ex_pystack_t*const restrict this,const shinsei_ex_pystack_t*const restrict src)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_attachUnsafe(shinsei_ex_pystack_t*const restrict this,const shinsei_ex_pystack_t*const restrict src)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_attachValue(shinsei_ex_pystack_t*const restrict this,const int_fast32_t ctrl,const size_t size,const size_t cap,PyObject**const ptr)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_attachValueUnsafe(shinsei_ex_pystack_t*const restrict this,const int_fast32_t ctrl,const size_t size,const size_t cap,PyObject**const ptr)_SHINSEI_OS_NOEXCEPT;

_SHINSEI_LIB_API void shinsei_ex_pystack_t_freeData(shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API void shinsei_ex_pystack_t_freeDataUnsafe(shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;

// Static Factories
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_as(shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_asCapacity(shinsei_ex_pystack_t*const restrict this,const size_t cap)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_asAssign(shinsei_ex_pystack_t*const restrict this,const shinsei_ex_pystack_t*const restrict src)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_asAssignUnsafe(shinsei_ex_pystack_t*const restrict this,const shinsei_ex_pystack_t*const restrict src)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API void shinsei_ex_pystack_t_asMove(shinsei_ex_pystack_t*const restrict this,shinsei_ex_pystack_t* const restrict src)_SHINSEI_OS_NOEXCEPT;

// Inline Factories
_SHINSEI_LIB_API void shinsei_ex_pystack_t_inl(shinsei_ex_pystack_t*const restrict this,const size_t cap)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API void shinsei_ex_pystack_t_inlCapacity(shinsei_ex_pystack_t*const restrict this,const size_t cap)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API void shinsei_ex_pystack_t_inlAssign(shinsei_ex_pystack_t*const restrict this,const shinsei_ex_pystack_t*const restrict src)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API void shinsei_ex_pystack_t_inlAssignUnsafe(shinsei_ex_pystack_t*const restrict this,const shinsei_ex_pystack_t*const restrict src)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API void shinsei_ex_pystack_t_inlMove(shinsei_ex_pystack_t*const restrict this,shinsei_ex_pystack_t* const restrict src)_SHINSEI_OS_NOEXCEPT;

// Property Accessors
_SHINSEI_LIB_API bool shinsei_ex_pystack_t_inlined(const shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API int_fast32_t shinsei_ex_pystack_t_getCtrl(const shinsei_ex_pystack_t*const restrict this)_SHINSEI_OS_NOEXCEPT;
_SHINSEI_LIB_API void shinsei_ex_pystack_t_setCtrl(shinsei_ex_pystack_t*const restrict this,const int_fast32_t ctrl)_SHINSEI_OS_NOEXCEPT;

#ifdef _SHINSEI_OS_CPP
}
#undef this
#endif