#pragma once

#include"shinsei/minimal/file.h"
#include"shinsei/.internal/tag.hpp"

namespace shinsei{
	constexpr int FILE_TYPE_ILLEGAL=::SHINSEI_FILE_TYPE_ILLEGAL;
	constexpr int FILE_TYPE_FILE=::SHINSEI_FILE_TYPE_FILE;
	constexpr int FILE_TYPE_DIRECTORY=::SHINSEI_FILE_TYPE_DIRECTORY;
	constexpr int FILE_TYPE_NEED_MORE_BUFFER=::SHINSEI_FILE_TYPE_NEED_MORE_BUFFER;
	
	constexpr int FILE_OPEN_READ=::SHINSEI_FILE_OPEN_READ;
	constexpr int FILE_OPEN_WRITE=::SHINSEI_FILE_OPEN_WRITE;
	constexpr int FILE_OPEN_APPEND=::SHINSEI_FILE_OPEN_APPEND;
	constexpr int FILE_OPEN_READWRITE=::SHINSEI_FILE_OPEN_READWRITE;
	constexpr int FILE_OPEN_WRITEREAD=::SHINSEI_FILE_OPEN_WRITEREAD;
	constexpr int FILE_OPEN_READAPPEND=::SHINSEI_FILE_OPEN_READAPPEND;
	
	constexpr int FILE_OWNER_DEFAULT=::SHINSEI_FILE_OWNER_DEFAULT;
	constexpr int FILE_OWNER_CURRENT=::SHINSEI_FILE_OWNER_CURRENT;
	constexpr int FILE_OWNER_HIGHEST=::SHINSEI_FILE_OWNER_HIGHEST;
	
	constexpr int FILE_EOF=::SHINSEI_FILE_EOF;
	
	constexpr int FILE_SEEK_SET=::SHINSEI_FILE_SEEK_SET;
	constexpr int FILE_SEEK_CUR=::SHINSEI_FILE_SEEK_CUR;
	constexpr int FILE_SEEK_END=::SHINSEI_FILE_SEEK_END;
	
}