#pragma once

#include"shinsei/.internal/usage.h"
#ifdef _SHINSEI_OS_CPP
extern "C"{
#endif

#ifdef _SHINSEI_OS_CONSTEXPR
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_TYPE_ILLEGAL=0;
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_TYPE_FILE=1;
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_TYPE_DIRECTORY=2;
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_TYPE_NEED_MORE_BUFFER=3;
	
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_OPEN_READ=0; // rb
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_OPEN_WRITE=1; // wb
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_OPEN_APPEND=2; // ab
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_OPEN_READWRITE=3; // rb+
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_OPEN_WRITEREAD=4; // wb+
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_OPEN_READAPPEND=5; // ab+
	
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_OWNER_DEFAULT=0; // System default behavior
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_OWNER_CURRENT=1; // Always be current user even have high privilege
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_OWNER_HIGHEST=2; // Be in highest privilege if current have
	
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_EOF=-1;
	
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_SEEK_SET=0;
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_SEEK_CUR=1;
	static _SHINSEI_OS_CONSTEXPR int SHINSEI_FILE_SEEK_END=2;
	
#else
	#define SHINSEI_FILE_TYPE_ILLEGAL 0
	#define SHINSEI_FILE_TYPE_FILE 1
	#define SHINSEI_FILE_TYPE_DIRECTORY 2
	#define SHINSEI_FILE_TYPE_NEED_MORE_BUFFER 3
	
	#define SHINSEI_FILE_OPEN_READ 0
	#define SHINSEI_FILE_OPEN_WRITE 1
	#define SHINSEI_FILE_OPEN_APPEND 2
	#define SHINSEI_FILE_OPEN_READWRITE 3
	#define SHINSEI_FILE_OPEN_WRITEREAD 4
	#define SHINSEI_FILE_OPEN_READAPPEND 5
	
	#define SHINSEI_FILE_OWNER_DEFAULT 0
	#define SHINSEI_FILE_OWNER_CURRENT 1
	#define SHINSEI_FILE_OWNER_HIGHEST 2
	
	#define SHINSEI_FILE_EOF (-1)
	
	#define SHINSEI_FILE_SEEK_SET 0
	#define SHINSEI_FILE_SEEK_CUR 1
	#define SHINSEI_FILE_SEEK_END 2
	
#endif

#ifdef _SHINSEI_OS_CPP
}
#endif