#pragma once

#include"shinsei/minimal/io.h"

namespace shinsei{
	static _SHINSEI_OS_CONSTEXPR size_t PRINT_BUFFER_SIZE_U8=::SHINSEI_PRINT_BUFFER_SIZE_U8;
	static _SHINSEI_OS_CONSTEXPR size_t PRINT_BUFFER_SIZE_U16=::SHINSEI_PRINT_BUFFER_SIZE_U16;
	static _SHINSEI_OS_CONSTEXPR size_t PRINT_BUFFER_SIZE_U32=::SHINSEI_PRINT_BUFFER_SIZE_U32;
	
	static _SHINSEI_OS_CONSTEXPR size_t PRINT_BUFFER_SIZE_INT8=::SHINSEI_PRINT_BUFFER_SIZE_INT8;
	static _SHINSEI_OS_CONSTEXPR size_t PRINT_BUFFER_SIZE_UINT8=::SHINSEI_PRINT_BUFFER_SIZE_UINT8;
	static _SHINSEI_OS_CONSTEXPR size_t PRINT_BUFFER_SIZE_INT16=::SHINSEI_PRINT_BUFFER_SIZE_INT16;
	static _SHINSEI_OS_CONSTEXPR size_t PRINT_BUFFER_SIZE_UINT16=::SHINSEI_PRINT_BUFFER_SIZE_UINT16;
	static _SHINSEI_OS_CONSTEXPR size_t PRINT_BUFFER_SIZE_INT32=::SHINSEI_PRINT_BUFFER_SIZE_INT32;
	static _SHINSEI_OS_CONSTEXPR size_t PRINT_BUFFER_SIZE_UINT32=::SHINSEI_PRINT_BUFFER_SIZE_UINT32;
	static _SHINSEI_OS_CONSTEXPR size_t PRINT_BUFFER_SIZE_INT64=::SHINSEI_PRINT_BUFFER_SIZE_INT64;
	static _SHINSEI_OS_CONSTEXPR size_t PRINT_BUFFER_SIZE_UINT64=::SHINSEI_PRINT_BUFFER_SIZE_UINT64;
	static _SHINSEI_OS_CONSTEXPR size_t PRINT_BUFFER_SIZE_SIZE=::SHINSEI_PRINT_BUFFER_SIZE_SIZE;
	static _SHINSEI_OS_CONSTEXPR size_t PRINT_BUFFER_SIZE_PTR=::SHINSEI_PRINT_BUFFER_SIZE_PTR;
	
	static _SHINSEI_OS_CONSTEXPR size_t TEXT_TRUE_LEN=::SHINSEI_TEXT_TRUE_LEN;
	static _SHINSEI_OS_CONSTEXPR size_t TEXT_FALSE_LEN=::SHINSEI_TEXT_FALSE_LEN;
	
	static _SHINSEI_OS_CONSTEXPR const wchar_t* TEXT_TRUE_W=::SHINSEI_TEXT_TRUE_W;
	static _SHINSEI_OS_CONSTEXPR const char8_t* TEXT_TRUE_U8=::SHINSEI_TEXT_TRUE_U8;
	static _SHINSEI_OS_CONSTEXPR const char16_t* TEXT_TRUE_U16=::SHINSEI_TEXT_TRUE_U16;
	static _SHINSEI_OS_CONSTEXPR const char32_t* TEXT_TRUE_U32=::SHINSEI_TEXT_TRUE_U32;
	
	static _SHINSEI_OS_CONSTEXPR const wchar_t* TEXT_FALSE_W=::SHINSEI_TEXT_FALSE_W;
	static _SHINSEI_OS_CONSTEXPR const char8_t* TEXT_FALSE_U8=::SHINSEI_TEXT_FALSE_U8;
	static _SHINSEI_OS_CONSTEXPR const char16_t* TEXT_FALSE_U16=::SHINSEI_TEXT_FALSE_U16;
	static _SHINSEI_OS_CONSTEXPR const char32_t* TEXT_FALSE_U32=::SHINSEI_TEXT_FALSE_U32;
	
}