#pragma once
#include"shinsei/.internal/usage.h"
#include"shinsei/.internal/wchar.h"
#include<uchar.h>

#ifdef _SHINSEI_OS_CPP
extern "C"{
#endif

#ifdef _SHINSEI_OS_CONSTEXPR
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_PRINT_BUFFER_SIZE_U8=4096;
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_PRINT_BUFFER_SIZE_U16=2048;
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_PRINT_BUFFER_SIZE_U32=1024;
	
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_PRINT_BUFFER_SIZE_INT8=4;
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_PRINT_BUFFER_SIZE_UINT8=4;
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_PRINT_BUFFER_SIZE_INT16=8;
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_PRINT_BUFFER_SIZE_UINT16=8;
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_PRINT_BUFFER_SIZE_INT32=12;
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_PRINT_BUFFER_SIZE_UINT32=12;
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_PRINT_BUFFER_SIZE_INT64=24;
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_PRINT_BUFFER_SIZE_UINT64=24;
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_PRINT_BUFFER_SIZE_SIZE=24;
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_PRINT_BUFFER_SIZE_PTR=24;
	
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_TEXT_TRUE_LEN=4;
	static _SHINSEI_OS_CONSTEXPR size_t SHINSEI_TEXT_FALSE_LEN=5;
	
	static _SHINSEI_OS_CONSTEXPR const wchar_t SHINSEI_TEXT_TRUE_W[]=L"true";
	static _SHINSEI_OS_CONSTEXPR const char8_t SHINSEI_TEXT_TRUE_U8[]=u8"true";
	static _SHINSEI_OS_CONSTEXPR const char16_t SHINSEI_TEXT_TRUE_U16[]=u"true";
	static _SHINSEI_OS_CONSTEXPR const char32_t SHINSEI_TEXT_TRUE_U32[]=U"true";
	static _SHINSEI_OS_CONSTEXPR const wchar_t SHINSEI_TEXT_FALSE_W[]=L"false";
	static _SHINSEI_OS_CONSTEXPR const char8_t SHINSEI_TEXT_FALSE_U8[]=u8"false";
	static _SHINSEI_OS_CONSTEXPR const char16_t SHINSEI_TEXT_FALSE_U16[]=u"false";
	static _SHINSEI_OS_CONSTEXPR const char32_t SHINSEI_TEXT_FALSE_U32[]=U"false";
#else
	#define SHINSEI_PRINT_BUFFER_SIZE_U8 ((size_t)4096)
	#define SHINSEI_PRINT_BUFFER_SIZE_U16 ((size_t)2048)
	#define SHINSEI_PRINT_BUFFER_SIZE_U32 ((size_t)1024)
	
	#define SHINSEI_PRINT_BUFFER_SIZE_INT8 ((size_t)4)
	#define SHINSEI_PRINT_BUFFER_SIZE_UINT8 ((size_t)4)
	#define SHINSEI_PRINT_BUFFER_SIZE_INT16 ((size_t)8)
	#define SHINSEI_PRINT_BUFFER_SIZE_UINT16 ((size_t)8)
	#define SHINSEI_PRINT_BUFFER_SIZE_INT32 ((size_t)12)
	#define SHINSEI_PRINT_BUFFER_SIZE_UINT32 ((size_t)12)
	#define SHINSEI_PRINT_BUFFER_SIZE_INT64 ((size_t)24)
	#define SHINSEI_PRINT_BUFFER_SIZE_UINT64 ((size_t)24)
	#define SHINSEI_PRINT_BUFFER_SIZE_SIZE ((size_t)24)
	#define SHINSEI_PRINT_BUFFER_SIZE_PTR ((size_t)24)
	
	#define SHINSEI_TEXT_TRUE_LEN ((size_t)4)
	#define SHINSEI_TEXT_FALSE_LEN ((size_t)5)
	
	#define SHINSEI_TEXT_TRUE_W L"true"
	#define SHINSEI_TEXT_TRUE_U8 u8"true"
	#define SHINSEI_TEXT_TRUE_U16 u"true"
	#define SHINSEI_TEXT_TRUE_U32 U"true"
	#define SHINSEI_TEXT_FALSE_W L"false"
	#define SHINSEI_TEXT_FALSE_U8 u8"false"
	#define SHINSEI_TEXT_FALSE_U16 u"false"
	#define SHINSEI_TEXT_FALSE_U32 U"false"
#endif

#ifdef _SHINSEI_OS_CPP
}
#endif